### ISSUE TITLE
ParserVMM3a has error for use with multiple FECs

### ISSUE THREAD

**Issue by dorotheapfeiffer** [ess-dmsc/event-formation-unit#375]
In the case that the frame counter of the present UDP frame is not the expected frame counter, all time stamps are deleted. This is not totally wrong in the case of one FEC (since with one FEC  a frame counter error is indicative of data loss). But in the case of two or more FECs it is just wrong. The correct implementation would be to store the last frame counter per FEC.

For the moment suffices it to just comment out the time stamp deletion.

 if (pd.nextFrameCounter != hdr.frameCounter) {
    if(hdr.frameCounter > pd.nextFrameCounter) {
      if(stats.ParserGoodFrames > 0) {
        stats.ParserFrameMissingErrors +=
         (hdr.frameCounter - pd.nextFrameCounter);
        XTRACE(PROCESS, WAR, "ParserFrameMissingErrors: fc %d, next fc %d",
        hdr.frameCounter, pd.nextFrameCounter);
      }
    }
    else {
      if (pd.nextFrameCounter - hdr.frameCounter > 0x0FFFFFFF) {
        stats.ParserFramecounterOverflows++;
        XTRACE(PROCESS, DEB, "ParserFramecounterOverflows: fc %d, next fc %d",
          hdr.frameCounter, pd.nextFrameCounter);
      }
      else {
        stats.ParserFrameSeqErrors++;
        XTRACE(PROCESS, WAR, "ParserFrameSeqErrors: fc %d, next fc %d",
          hdr.frameCounter, pd.nextFrameCounter);
/*
        for(int vmmid=0; vmmid < MaxVMMs; vmmid++) {
          markers[(pd.fecId - 1) * MaxVMMs + vmmid].fecTimeStamp = 0;
          markers[(pd.fecId - 1) * MaxVMMs + vmmid].calcTimeStamp = 0;
        }
        */
      }
    }
  }

**Comment by mortenjc** [comment]
Hey

Your naming the branch using '#' broke the build. It took some time
to figure out that this was why the build failed. I have renamed it
to issue_375 instead ;-)

I'll wait for the jenkins job to pass before pulling in the changes. I suspect (hope)
that a unit test will fail and that something needs to be fixed, but let's see.

-M

From: Dorothea Pfeiffer ***@***.***>
Reply-To: ess-dmsc/event-formation-unit ***@***.***>
Date: Friday, 12 March 2021 at 16:05
To: ess-dmsc/event-formation-unit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ess-dmsc/event-formation-unit] ParserVMM3a has error for use with multiple FECs (#375)


In the case that the frame counter of the present UDP frame is not the expected frame counter, all time stamps are deleted. This is not totally wrong in the case of one FEC (since with one FEC a frame counter error is indicative of data loss). But in the case of two or more FECs it is just wrong. The correct implementation would be to store the last frame counter per FEC.

For the moment suffices it to just comment out the time stamp deletion.

if (pd.nextFrameCounter != hdr.frameCounter) {
if(hdr.frameCounter > pd.nextFrameCounter) {
if(stats.ParserGoodFrames > 0) {
stats.ParserFrameMissingErrors +=
(hdr.frameCounter - pd.nextFrameCounter);
XTRACE(PROCESS, WAR, "ParserFrameMissingErrors: fc %d, next fc %d",
hdr.frameCounter, pd.nextFrameCounter);
}
}
else {
if (pd.nextFrameCounter - hdr.frameCounter > 0x0FFFFFFF) {
stats.ParserFramecounterOverflows++;
XTRACE(PROCESS, DEB, "ParserFramecounterOverflows: fc %d, next fc %d",
hdr.frameCounter, pd.nextFrameCounter);
}
else {
stats.ParserFrameSeqErrors++;
XTRACE(PROCESS, WAR, "ParserFrameSeqErrors: fc %d, next fc %d",
hdr.frameCounter, pd.nextFrameCounter);
/*
for(int vmmid=0; vmmid < MaxVMMs; vmmid++) {
markers[(pd.fecId - 1) * MaxVMMs + vmmid].fecTimeStamp = 0;
markers[(pd.fecId - 1) * MaxVMMs + vmmid].calcTimeStamp = 0;
}
*/
}
}
}

**Comment by mortenjc** [comment]
Job passed, I have added \todos in the comments so we won't frget this, but hey maybe we will never need this.
